services:
  health-to-sfs:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: health-to-sfs
    restart: unless-stopped
    networks:
      - frontend
    ports:
      - 9003:8080
    environment:
      API_SECRET: ${API_SECRET}
      CONFIG_PATH: "/config/config.yaml"
    volumes:
      - ../config:/config

networks:
  frontend:
    external: true
